Class {
	#name : 'RaylibMatrix',
	#superclass : 'FFIStructure',
	#category : 'RayLib',
	#package : 'RayLib'
}

{ #category : 'field definition' }
RaylibMatrix class >> fieldsDesc [
	^ #(
		float m0;
		float m4;
		float m8;
		float m12;  
    	float m1; 
	float m5; 
	float m9; 
	float m13;  
    	float m2; 
	float m6;
	float m10;
	float m14; 
    	float m3; 
	float m7;
	float m11;
	float m15; 
	)
]
